{% set name = "gensim" %}
{% set version = "3.8.3" %}
{% set sha256 = "786adb0571f75114e9c5f7a31dd2e6eb39a9791f22c8757621545e2ded3ea367" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 5
  skip: true  # [py==27]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python <=3.9                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy =1.26.4                               # [build_platform != target_platform]
    - libxcrypt  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - setuptools
    - pip
  host:
    - python <=3.9
    - pip
    - numpy =1.26.4
    - scipy >=0.18.1,<1.13
    - six >=1.5.0
    - smart_open >=1.8.1  
    - setuptools
    - libxcrypt  # [linux or arm64]      
  run:
    - python <=3.9
    - {{ pin_compatible('numpy') }}
    - scipy >=0.18.1,<1.13
    - six >=1.5.0
    - smart_open >=1.8.1

test:
  imports:
    - gensim
    - gensim.corpora
    - gensim.models
    - gensim.parsing
    - gensim.scripts
    - gensim.similarities
    - gensim.test
    - gensim.topic_coherence
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/RaRe-Technologies/gensim
  license: LGPL-2.1-only
  license_file: COPYING
  summary: Topic Modelling for Humans
  description: |
    Gensim is a Python library for topic modelling, document indexing
    and similarity retrieval with large corpora.
    Target audience is the natural language processing (NLP)
    and information retrieval (IR) community.
  doc_url: http://radimrehurek.com/gensim/
  dev_url: https://github.com/RaRe-Technologies/gensim

extra:
  recipe-maintainers:
    - souravsingh
    - mpenkov
    - HeavyTony2
