{% set name = "gensim" %}
{% set version = "4.1.0" %}
{% set sha256 = "0b09983048a97c7915ab50500bc53eeec438d26366041598709ec156db3eef1f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py==27]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy >=1.11.3
    - scipy >=0.18.1
    - six >=1.5.0
    - smart_open >=1.8.1
  run:
    - dataclasses  # [py<37]
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.18.1
    - six >=1.5.0
    - smart_open >=1.8.1

test:
  imports:
    - gensim
    - gensim.corpora
    - gensim.models
    - gensim.parsing
    - gensim.scripts
    - gensim.similarities
    - gensim.test
    - gensim.topic_coherence

about:
  home: http://github.com/RaRe-Technologies/gensim
  license: LGPL-2.1-only
  license_file: COPYING
  summary: Topic Modelling for Humans
  description: |
    Gensim is a Python library for topic modelling, document indexing
    and similarity retrieval with large corpora.
    Target audience is the natural language processing (NLP)
    and information retrieval (IR) community.
  doc_url: http://radimrehurek.com/gensim/
  dev_url: https://github.com/RaRe-Technologies/gensim

extra:
  recipe-maintainers:
    - souravsingh
    - mpenkov
