{% set version = "3.8.1" %}

package:
  name: gensim
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gensim/gensim-{{ version }}.tar.gz
  sha256: 33277fc0a8d7b0c7ce70fcc74bb82ad39f944c009b334856c6e86bf552b1dfdc

build:
  number: 2
  skip: true  # [py27]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - scipy >=0.18.1
    - six >=1.5.0
    - smart_open >=1.2.1
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.18.1
    - six >=1.5.0
    - smart_open >=1.2.1

test:
  requires:
    - nose
    - testfixtures
    - morfessor
    # - scikit-learn
    - pyemd
    - mock
    - boto3
    - python-levenshtein
  imports:
    - gensim
    - gensim.corpora
    - gensim.models
    - gensim.models.wrappers
    - gensim.parsing
    - gensim.scripts
    - gensim.similarities
    # - gensim.sklearn_api
    - gensim.summarization
    - gensim.test
    - gensim.topic_coherence
  files:
    - forge_test.sh
  commands:
    - time bash ./forge_test.sh  # [not win]
    - nosetests --exe -v gensim  # [win]

about:
  home: http://github.com/RaRe-Technologies/gensim
  license: LGPL-2.1
  license_file: COPYING
  license_family: LGPL
  summary: 'Topic Modelling for Humans'
  description: |
    Gensim is a Python library for topic modelling, document indexing
    and similarity retrieval with large corpora.
    Target audience is the natural language processing (NLP)
    and information retrieval (IR) community.
  doc_url: http://radimrehurek.com/gensim/
  dev_url: https://github.com/RaRe-Technologies/gensim

extra:
  recipe-maintainers:
    - souravsingh
    - mpenkov
